### ISSUE TITLE
User SafeERC20 for ERC20 operations

### ISSUE THREAD

**Issue by alonmuroch** [bloxapp/ssv-network#24]
@adamzigdon @vadiminc @lior-blox

**Comment by adamzigdon** [comment]
@alonmuroch SafeERC20 is a library that should help you safely interact with foreign tokens that don't necessarily implement ERC20 correctly.
Uniswap had a problem with the BNB token on Ethereum because its `transfer` method didn't return a value as expected in the standard (for some reason `transferFrom` did).
The library encapsulates the function call and assumes that the transaction was successful if it neither returned false nor reverted, allowing the methods to lack a return value.
